# serverless.yml
bandtent-v3:
  component: '@sls-next/serverless-component@latest'
  inputs:
    name:
      defaultLambda: DefaultLambda
      imageLambda: ImageLambda
    bucketRegion: 'eu-central-1'
    cloudfront:
      comment: 'next deploy'
